version: '3'

services:
  web:
    env_file:
      - ./.env  
    environment:
      - MONGO_DB_URL=db
    build: ./cmd/subscriberWebAPI
    ports:
      - 5000:5000
    depends_on:
      - db
      - monitor
  monitor:
    env_file:
      - ./.env  
    environment:
      - MONGO_DB_URL=db
    build: ./cmd/currencyMonitor
    depends_on:
      - db
  db:
    image: "mongo:latest"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
